In [47]:
import numpy as np
from PIL import Image

lis = []

for i in range(7,-1,-1):
    res = b'\x01'[0]<<i
    lis.append(res)
    
print(lis)

[128, 64, 32, 16, 8, 4, 2, 1]


In [48]:
def spit(num):
    for i in lis:
        if num & i == 0:
            print(0,end=' ')
        else:
            print(1,end=' ')
    print("")

In [53]:
by = 'Hello world'
for i in by:
    spit(ord(i))

0 1 0 0 1 0 0 0 
0 1 1 0 0 1 0 1 
0 1 1 0 1 1 0 0 
0 1 1 0 1 1 0 0 
0 1 1 0 1 1 1 1 
0 0 1 0 0 0 0 0 
0 1 1 1 0 1 1 1 
0 1 1 0 1 1 1 1 
0 1 1 1 0 0 1 0 
0 1 1 0 1 1 0 0 
0 1 1 0 0 1 0 0 


In [72]:
pic = Image.open('pup.jpg')
arr = np.asarray(pic)
arr.shape

'1'

In [105]:
s_string = 'hello'
e_string = ':^DATA:END'

def write_img(img):
    #a,b,c = img.shape
    b=0
    
    for s in s_string:
        for i in lis:
            if ord(s) & i == 0:
                # Check if the first bit is not zero
                if img[0][b][0]%2 != 0:
                    img[0][b][0] += 1
            else:
                #check if first bit is not one
                if img[0][b][0]%2 == 0:
                    img[0][b][0] += 1
            b += 1

In [106]:
def read_img(img):
    b = 0
    str = []
    
    for i in range(5):
        ch = 0
        for j in lis:
            num = arr[0][b][0]
            if num%2 != 0:
                ch += j
            b += 1
        print(ch)
        str.append(chr(ch))
    
    print(str)
        

In [115]:
arr = np.zeros((1,50,1),np.int8)+8
write_img(arr)
read_img(arr)


104
101
108
108
111
['h', 'e', 'l', 'l', 'o']


In [116]:
print(arr[0,:8,0])
print(arr[0,8:16,0])
print(arr[0,16:24,0])

[8 9 9 8 9 8 8 8]
[8 9 9 8 8 9 8 9]
[8 9 9 8 9 9 8 8]
